### PR TITLE
April newsletter

### PR DESCRIPTION
**Pull request by davidfischer**
* Any news?
* Does Brightscope have any open positions?
* I guess it's time to plan our next workshop

### CODE REVIEW

**Comment by willingc** [comment]
+1 Thanks @davidfischer :ocean:

**Comment by macro1** [comment]
@davidfischer, BrightScope is still accepting applications for web developer. We'll probably be finishing up interviews in a week or two.

**Comment by willingc** [comment]
@davidfischer Just came across this DjangoCon post. CFP open until May 15th. First time speakers encouraged. Financial Aid available.

**Comment by davidfischer** [comment]
I pushed some updates based on the feedback. I'm happy to do these updates but if anyone wants to push commits to this branch or any future newsletter branch, don't feel like I have a monopoly on the newsletter.

**Comment by macro1** [comment]
:tophat:

**Comment by willingc** [comment]
@davidfischer Being thoughtful :) I was actually just throwing the info over the wall to you since I wasn't sure if I would have the time to write up and commit. Please let us know if you would like anything in particular for us to bring back from PyCon :)

**Comment by pydanny** [comment]
Also for DjangoCon, you might want to mention the new non-profit community-driven Django Events Foundation North America (DEFNA) running DjangoCon, the increase in transparency for the event (much needed), the focus on lower prices (HOORAY!), and the need for sponsors to help make it happen.

**Comment by davidfischer** [comment]
Have fun at PyCon guys. I don't need anything from Montreal but I hope you guys have a great time. The newsletter will go out today.

**Comment by davidfischer** [comment]
@pydanny I mentioned DEFNA but I'll add a sentence on what that means for the event.

**Comment by pydanny** [comment]
I'm really excited about the new leadership (Jeff Triplet / DEFNA). I know him personally, and know that the conference is in much better hands. Unlike the last few years, I feel a lot more comfortable recommending the event to attendees and sponsors. In fact, Jeff is trying to work the numbers so that with enough sponsorship they can drop the prices even further, making the event more accessible to those who need it the most.

**Pull request merged**
